### ISSUE TITLE
欠点入力画面の修正

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-ios#100]
方向はデフォルトで左が選択されているように、
全幅のを選択した場合は幅（始）、幅（終）が入力出来ないようにしてください。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 変更しました。バージョン1.0 (57)でご確認ください

**Comment by tsubasamatsumoto** [comment]
方向が左の時、幅の終わりがデフォルトで布の幅が入っている。
幅の終わりの初期値はゼロでお願いします。

**Comment by tsubasamatsumoto** [comment]
もう一つ。
幅を持っていない欠点（点欠点）は幅（始）だけに入力します。幅（終）を入力しない（ゼロ）の場合は終了できるようにしてください。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 
> 方向が左の時、幅の終わりがデフォルトで布の幅が入っている。
幅の終わりの初期値はゼロでお願いします。

ゼロにしました

> 幅を持っていない欠点（点欠点）は幅（始）だけに入力します。幅（終）を入力しない（ゼロ）の場合は終了できるようにしてください。

幅（終）はゼロの場合は保存する時に幅（始）と同じく保存されるようにしました

バージョン 1.0 (59)でご確認ください

**Comment by tsubasamatsumoto** [comment]
OK
