### ISSUE TITLE
検査開始、終了時の設定画面での単位修正お願いします。

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-ios#102]
![img_0232](https://user-images.githubusercontent.com/19566850/33371035-c8542a40-d53c-11e7-9d2a-9b07d39c2cd3.PNG)

**Comment by tsubasamatsumoto** [comment]
タテ密度、ヨコ密度の単位『（ｍ）、（ｃｍ）』はいらないです。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 修正しました。バージョン 1.0 (62)でご確認ください

**Comment by tsubasamatsumoto** [comment]
OK
