### ISSUE TITLE
検査やり直しでのエラー表示

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-ios#103]
![img_0233](https://user-images.githubusercontent.com/19566850/33464233-9e2994fa-d684-11e7-9d56-ff68647ec571.PNG)

**Comment by tsubasamatsumoto** [comment]
検査やり直しで検査開始設定後、このようなエラーがでました。確認お願いします。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto このようなエラーまで行けるフローは動画で撮っていただけますか？

**Comment by tsubasamatsumoto** [comment]
動画をスラックにアップしました。

**Comment by tsubasamatsumoto** [comment]
ロットが検査済みなのにロールをやり直したため起きるエラー？

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 修正しました。アプリアップデート必要ないです

**Comment by tsubasamatsumoto** [comment]
エラーがでなくなりました。
