### ISSUE TITLE
精錬でバーコードを読み込みで間違えているところを修正してください。

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-ios#105]
①織布　前に送ったCSVの"code"の部分が織布工場のNoだと思う。
　　　　丸井２で入るはずが宮米J2で入る。

②規格の部分の幅と長さのところが違うと思う。
　　　　幅が0cm　長さに幅が入っている。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto サンプルのロールバーコードをアップしていただけますか？

**Comment by tsubasamatsumoto** [comment]
![img_5338](https://user-images.githubusercontent.com/19566850/33587377-2eefaf68-d9b1-11e7-8048-f10ca131eb13.JPG)

**Comment by tsubasamatsumoto** [comment]
これを読み込むと織布がSGとなる。本当は丸井１。
規格の部分は0cm×198mとなる。本当は198m×60m

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 
> 規格の部分は0cm×198mとなる。本当は198m×60m

修正しました。新規ロールのみで表示されます

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 
> これを読み込むと織布がSGとなる。本当は丸井１

修正しました。ご確認ください

**Comment by tsubasamatsumoto** [comment]
OK
