### ISSUE TITLE
欠点登録後、検査の測長データがおかしくなる現象解析をお願いします。

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-ios#106]
①登録前
![img_5454](https://user-images.githubusercontent.com/19566850/33820804-78deb762-de94-11e7-98c9-7c59ea067a0a.JPG)
②登録中
![img_5455](https://user-images.githubusercontent.com/19566850/33820814-898efc16-de94-11e7-8b0d-8cd053862f57.JPG)
③登録済
![img_5456](https://user-images.githubusercontent.com/19566850/33820824-99908c10-de94-11e7-8181-21437b5e8d37.JPG)
④検査画面→測長がおかしい
![img_5457](https://user-images.githubusercontent.com/19566850/33820836-a4f09dca-de94-11e7-93fb-061461858eb4.JPG)

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto こちらについて動画撮っていただけますか？私の方で出てこないです。あと、その時にPLCが動いてますか？

**Comment by tsubasamatsumoto** [comment]
PLCは動いている状態です。動画をがんばって取ってみます。

**Comment by tsubasamatsumoto** [comment]
動画撮れました。2/26にSlackに動画をUPしました。

**Comment by take-iwa** [comment]
何度か試して出てないと思うので、問題ないかと思います。
