### ISSUE TITLE
アプリ出荷で反No.に記載されている疋数を検査での疋数に変更してください。

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-ios#108]
![img_0250](https://user-images.githubusercontent.com/19566850/33825268-76814344-dea4-11e7-9721-dafd520e9ca3.PNG)
この写真だと91129314-1-4（18）→91129314-1-4（5）　（5疋巻きなので）

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 修正しました。バージョン1.0 (67)でご確認ください

**Comment by tsubasamatsumoto** [comment]
OK、ありがとうございます
