### ISSUE TITLE
再検で新しいロールを作ったときに出るエラーの分析をお願いします。

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-ios#111]
![ios](https://user-images.githubusercontent.com/19566850/35429675-71373348-02b8-11e8-9952-a913ee4380f9.png)
アプリをアップデートして91220203-1Bを検査してメータが余ったので新しいロールを作ったらこのエラーがでました。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 修正しました。バージョン1.0 (72)でご確認ください

**Comment by tsubasamatsumoto** [comment]
修正が確認できました。ありがとうございます。
