### ISSUE TITLE
精錬ロット作成でエラーが出るので修正お願いします。

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-ios#112]

**Comment by tsubasamatsumoto** [comment]
![ios 1](https://user-images.githubusercontent.com/19566850/36651397-22fe37e8-1aec-11e8-8026-28f045a3a51a.png)

**Comment by tsubasamatsumoto** [comment]
![ios](https://user-images.githubusercontent.com/19566850/36651410-2c36e788-1aec-11e8-931c-3c095f9087db.jpg)

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 修正しました。ご確認ください

**Comment by tsubasamatsumoto** [comment]
修正されていることが確認しました。ありがとうございます。
