### ISSUE TITLE
検査終了後に出るエラーの分析をお願いします。

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-ios#114]
検査を終了したときにこのエラー画面が表示されます。原因をおしえてください。
![img_0288](https://user-images.githubusercontent.com/19566850/36663125-eaf7c412-1b23-11e8-8519-c208bafde933.PNG)

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 修正しました。バージョン1.0 (72)でご確認ください

**Comment by tsubasamatsumoto** [comment]
修正が確認できました。ありがとうございます。
