### ISSUE TITLE
検査でカットして、そのあと検査してメータが余って『新しいロールを作りますか？』の表示部のメータが違うので修正してください。

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-ios#115]
211mのロールを検査していて、70mのところでアクション→カットして、検査をしたとき
141mが残りのロールの長さとなります。141mのロールを132m検査して終わった時、
残り9m余るので検査終了後にでるロール作成のメータは9mとなります。
今はカットした70mも含まれており79mとでます。
その時の写真も添付します。

**Comment by tsubasamatsumoto** [comment]
![img_0302](https://user-images.githubusercontent.com/19566850/36822243-641d8e86-1d3a-11e8-9cc3-57a31a3cce8e.PNG)

**Comment by take-iwa** [comment]
何度か試してみて、問題ないように思います。
