### ISSUE TITLE
精錬ロット作成時に、勝手にロットが作成される。

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-ios#116]
作業員がロット作成した以上にロットができている。

**Comment by tsubasamatsumoto** [comment]
[ログ.txt](https://github.com/MaruiorimonoTeam/seiren-ios/files/2118108/default.txt)

**Comment by take-iwa** [comment]
何度か確認して出なかったので、問題ないように思います。
