### ISSUE TITLE
検査中にアプリから長さを変更できるようにしたい

### ISSUE THREAD

**Issue by take-iwa** [MaruiorimonoTeam/seiren-ios#121]
アプリでポップアップ通知が表示された時、接続が切れるらしくPLCと長さが合わなくなる。
ズレたとしても長さを修正できるようにしたいです。

![img_0403_png_ __users_ooiwa_downloads](https://user-images.githubusercontent.com/23730555/45735666-a0a75c00-bc23-11e8-89d0-28435df0dc15.jpg)

**Comment by alexeypolitov** [comment]
@take-iwa 修正の手動でしょうか？

**Comment by take-iwa** [comment]
@alexeypolitov そうです。手動入力による変更で大丈夫です。

**Comment by alexeypolitov** [comment]
@take-iwa 検査中のみ変更できるようにしました。「長さ」をタップすればポップアップで変更できます。
バージョン1.0 (80)ご確認くさい。
