### ISSUE TITLE
検査結果を読み込めない問題

### ISSUE THREAD

**Issue by take-iwa** [MaruiorimonoTeam/seiren-ios#127]
@alexeypolitov 
いくつか検査結果を読み込めないバーコードがありました。
FAで検査カード確認すると情報はあるようです。

#77同様、こちらもお願いいたします。

![img_0115](https://user-images.githubusercontent.com/23730555/45938436-efc70580-c004-11e8-9a40-def0ace87ec0.PNG)
![img_0118](https://user-images.githubusercontent.com/23730555/45938439-f786aa00-c004-11e8-95c0-d7381b3a7c56.JPG)
![img_0119](https://user-images.githubusercontent.com/23730555/45938440-f786aa00-c004-11e8-8cff-2249e3a51e10.JPG)

読み込んだ時のlog
[テキスト-730CF28C839C-1.txt](https://github.com/MaruiorimonoTeam/seiren-ios/files/2409651/-730CF28C839C-1.txt)

**Comment by alexeypolitov** [comment]
@take-iwa こちらは #77 と同じ問題です。その時の依頼の修正でそうなりました。
最終的に正しい検索の仕組みは教えていただけますでしょうか？

**Comment by take-iwa** [comment]
カットとして読む場所が違っていました。こちらの認識不足でした。
![_835683588365838090dd8c768f912891e6312e3094c529283835363834292e786c73_](https://user-images.githubusercontent.com/23730555/46115086-7875b980-c230-11e8-9331-3daea76fef48.jpg)
