### ISSUE TITLE
ランキングは半自動で判別するようにしてください

### ISSUE THREAD

**Issue by kanayamatakuo** [MaruiorimonoTeam/seiren-ios#33]
欠点情報より
合格
　（A）
不合格
　作業者が選択
　　　（D）
　　　（E）

判断基準は後ほど連絡いたします。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 追加しました。バージョン 1.0 (61)でご確認ください

**Comment by tsubasamatsumoto** [comment]
![img_0235](https://user-images.githubusercontent.com/19566850/33478340-4de38684-d6cc-11e7-92e1-65f0901bc23f.PNG)
![img_0236](https://user-images.githubusercontent.com/19566850/33478352-54402924-d6cc-11e7-88c6-c2b6502ba67a.PNG)

**Comment by tsubasamatsumoto** [comment]
①重大欠点　の　013ヒマ段を入れたけど自動判別機能が特に出来る感じがしない。確認お願いします。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto DBで重大欠点でランキングは登録してなかったです。登録しておすすめに出るようになりました

**Comment by tsubasamatsumoto** [comment]
OK
