### ISSUE TITLE
検査終了後にラベルプリントもできるようにお願いします。（同じものを2枚）

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-ios#54]
![img_2906](https://cloud.githubusercontent.com/assets/19566850/23244269/68cad43a-f9c7-11e6-96f7-ab99fa281485.JPG)

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 修正しました。アップデートでご確認ください

**Comment by tsubasamatsumoto** [comment]
検査終了後にラベル印刷ができることが確認できました。

**Comment by tsubasamatsumoto** [comment]
ラベル印刷は2枚になりませんか？
プリントのページで2枚印刷の設定になっていればベスト。
できなければ印刷物が2枚あるようにすればいいので。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto できないです。手動で設定するしかないです

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 修正しました。バージョン 1.0 (59)でご確認ください

**Comment by tsubasamatsumoto** [comment]
OK、対応ありがとう。
