### ISSUE TITLE
出荷のアプリで出荷準備完了後にパレット内容の一覧が印刷されるようにしてください。

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-ios#55]
![img_2910](https://cloud.githubusercontent.com/assets/19566850/23245553/c175a5c0-f9d0-11e6-93bf-f6cb60e0ef19.JPG)

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto ご確認ください

**Comment by tsubasamatsumoto** [comment]
アプリで準備完了→出荷完了→印刷となっていますが、準備完了→印刷に変更はできますか？

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 「出荷完了」はウェブのみでやる予定ですか？それとも「出荷完了」自体必要ないですか？

**Comment by tsubasamatsumoto** [comment]
アプリ出荷で準備中→準備完了→出荷完了→印刷となっていますが、
印刷ボタンを別に作ることはできないでしょうか？
（印刷は準備完了後にできるようにしてほしいです）
右上のボタンは準備完了→出荷完了でお願いします。
出荷完了処理はWEBでもアプリでも出来るようします。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 印刷だ別でできるようにします。
出荷完了処理はロール追加・削除のことですか？

**Comment by tsubasamatsumoto** [comment]
出荷完了処理はアプリでいう出荷完了ボタンを押したときの動作のことを意味しています。
アプリでもWEBでもステータスを出荷完了に変えれるようにしてくださいということです。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto すでにそうなってます。アプリでもウェブでもです。

**Comment by tsubasamatsumoto** [comment]
OK
