### ISSUE TITLE
検査が全ておわったとき、完了のボタンが効かない

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-ios#73]
![img_3262](https://cloud.githubusercontent.com/assets/19566850/24856598/412444ca-1e20-11e7-91f9-651dc9c5d559.JPG)
このこの状態で完了を押しても何もならない。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 修正しました。アップデートでご確認ください

**Comment by tsubasamatsumoto** [comment]
アップデート確認しましたが、やはり完了ボタンが効かないです。
