### ISSUE TITLE
QRコードに入れてほしい情報があるのでいれてください。

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-ios#78]
検査後に発行されるラベル（ラベルプリンター）のQRに情報を入れてほしいです。
＜ＱＲコードに含んで欲しい情報＞
①品番
②反番
③製品長
④全巾欠点の有無
⑤精錬日
⑥検反日
⑦検反号機

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto QRの中に追加しました。ご確認下さい。

**Comment by tsubasamatsumoto** [comment]
全幅欠点の数がQRの中に反映されていないです。
![img_0230](https://user-images.githubusercontent.com/19566850/33204922-6c760f42-d148-11e7-84be-b37e39a550c7.PNG)
印刷されたものは全幅欠点数は２、QR内は１

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 
> ④全巾欠点の有無
なので「１」あり、「０」なしになってます。
全幅欠点数に入れる必要があるなら入れます

**Comment by tsubasamatsumoto** [comment]
④全巾欠点の有無ですが、全幅欠点の数でお願いします。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 変更しました

**Comment by tsubasamatsumoto** [comment]
OK
