### ISSUE TITLE
検査でロールの巻数量を超えた場合、新しい「ロールを作成しますか？」が出ないようにしてほしい

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-ios#81]
このとき長さ調整しなかった場合、検査表の①性量の長さ、②検査表の下の所にある長さは検査で測定した長さにしてください。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 修正しました。ご確認下さい

**Comment by tsubasamatsumoto** [comment]
![img_0191](https://user-images.githubusercontent.com/19566850/29061538-3e3ec2c0-7c59-11e7-8e3a-05a2fd6e3cbe.PNG)
![img_0192](https://user-images.githubusercontent.com/19566850/29061537-3e080dd4-7c59-11e7-91ea-3a91038b285f.PNG)

**Comment by tsubasamatsumoto** [comment]
検査終了時に長さが超えた場合は、ロール作成不要です。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 修正済みです。ご確認ください。

**Comment by tsubasamatsumoto** [comment]
OK
