### ISSUE TITLE
ラベル、QRの間違っている箇所を修正してください。

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-ios#82]
今わかっているのはQR内の精錬日、全巾欠点数

ラベル内は全巾欠点数

**Comment by alexeypolitov** [comment]
<img width="330" alt="screen shot 2017-08-08 at 11 01 41" src="https://user-images.githubusercontent.com/3468058/29053137-46b56bdc-7c29-11e7-94cc-feb15415fae2.png">


@tsubasamatsumoto 修正しました。ご確認下さい
