### ISSUE TITLE
検査でロールを作成した時の反Noの更新の仕方

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-ios#84]
検査終了後に巻量があまったときに新しくロールを作成するがそのロールの反No.が末尾の－１が増える仕様では無く数字が増えて作られるものにしてほしい

例：　今の仕様
－１－１
－１－１－１
－１－１－１－１

希望の仕様
ー１－１
－１－２
－１－３

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 修正済みです。ご確認ください

**Comment by tsubasamatsumoto** [comment]
OK
