### ISSUE TITLE
検査終了後のランク付け（ランクの種類）

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-ios#85]
ランクは
A
D
保留

保留の場合は検査カード、ラベルのランクの箇所は空白にしてください。
ただしサーバ内のデータとしてはDを入力してください。
（WEBでの格上げ処理によりサーバのデータをD→Aに変更する処理と絡んできます）

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto A/D/N/保留ランクにしました。A以外の場合は主欠点は登録必要となります

**Comment by tsubasamatsumoto** [comment]
保留の場合は検査カード、ラベルのランクの箇所は空白としてください。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 変更しました

**Comment by tsubasamatsumoto** [comment]
OK
