### ISSUE TITLE
検査終了時のエラーの確認をお願いします。

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-ios#96]
![img_0231](https://user-images.githubusercontent.com/19566850/33264600-985cd4d6-d3b1-11e7-8786-540457a50441.PNG)

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto こちらは毎回出てますか？それとももしかして終了ボタンに二回タップしてからこのような表示になりましたか？

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto このようなエラーまで行けるフローは動画で撮っていただけますか？

**Comment by tsubasamatsumoto** [comment]
状況が再現しないため一旦クローズします
