### ISSUE TITLE
検査のアクション→カットのアプリ動作の修正をお願いします。

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-ios#97]
カットしたらそれまでの検査履歴削除はOK。
カットをするとロールからそれまでの部分がカットされ捨てられます。
それまでの部分（長さ）を全部の長さから引いたものに変更する必要があります。
例：全部の長さ663m　　200mまで検査したがカットした場合は　463mに全部の長さが変わる。
それまでの検査データは破棄。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 修正しました。バージョン1.0 (57)でご確認ください

**Comment by tsubasamatsumoto** [comment]
OK、パーフェクト完璧
