### ISSUE TITLE
検査終了後「新しくロールを作る」をした時の動作を修正してください。

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-ios#98]
例
ロール（ロールNo.12345-1）900mあったときに300m巻いて検査終了し、新しくロールを作ったとき
①ロールNo.12345-1　→300m/300m
②ロールNo.12345-1-1　→　0/600m

今は①がロールNo.12345-1　→300m/900mというのになっています。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 修正しました。バージョン1.0 (57)でご確認ください

**Comment by tsubasamatsumoto** [comment]
ok
